# Generated by Django 5.2.12 on 2026-03-28 07:49

from django.db import migrations, models

def create_free_tier(apps, schema_editor):
    Tier = apps.get_model("subscriptions", "Tier")
    # Check if free tier already exists
    if not Tier.objects.filter(name="free").exists():
        Tier.objects.create(
            name="Free Plan",
            stripe_price_id=None,  # Free has no Stripe ID
            price=0,
            description="Free tier",
            is_default=True,
            level=0,
        )

def remove_free_tier(apps, schema_editor):
    Tier = apps.get_model("subscriptions", "Tier")
    Tier.objects.filter(is_default=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_usersubscription_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tier",
            name="level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tier",
            name="stripe_price_id",
            field=models.CharField(
                help_text="Stripe Price ID", max_length=255, null=True
            ),
        ),
        migrations.RunPython(create_free_tier, reverse_code=remove_free_tier),
    ]
